services:
  web:
    build: .
    ports:
      - "7999:8000"
    volumes:
      - /home/nic/projects/personal/images.pype.dev:/app
      # Mount your SSH private key from host to container
      # IMPORTANT: Replace '~/.skm/images-pype-dev' if this path is not exactly correct for your host.
      # This key file on your HOST must have permissions 600 (e.g., chmod 600 ~/.skm/images-pype-dev)
      - ./id_rsa:/home/appuser/.ssh/id_rsa:ro
    env_file: .env
    restart: unless-stopped
    # command: ["uv", "run", "app/shotput.py"]
